app/urls.py
from django.contrib import admin
from django.urls import include, path

from app.views import Index, AccountProfile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', AccountProfile.as_view(), name='account_profile'),
    path('', Index.as_view(), name='index'),
    path('url/', include('bitly.urls')),
]

bitly/urls.py
from django.urls import path

from bitly.views import get_or_create_url, redirect_by_url

app_name = "bitly"

urlpatterns = [
    path('create', get_or_create_url, name='create_url'),
    path('<int:pk>', redirect_by_url, name='redirect_by_url'),
    ]

bitly/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models


class BaseModel(models.Model):
    """
    Base abstract model for all models
    """
    class Meta:
        abstract = True
    create_date = models.DateField(null=True, default=datetime.date.today, editable=True)
    write_date = models.DateField(null=True, auto_now=True, editable=True)


class Url(BaseModel):
    base_url = models.URLField(max_length=2048, null=False, blank=False)
    short_url = models.URLField(max_length=128)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    counter = models.SmallIntegerField(null=True, blank=True, default=0)

bitly/forms.py
from django import forms

from bitly.models import Url


class UrlForm(forms.ModelForm):
    class Meta:
        model = Url
        fields = ['base_url']
        labels = {
            "base_url": "Enter your url"
        }

app/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = 'index.html'


class AccountProfile(TemplateView):
    template_name = 'account_profile.html'

bitly/views.py
import secrets

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpRequest
from django.shortcuts import render

from bitly.forms import UrlForm
from bitly.models import Url
from bitly.utils.constants import chars


@login_required
def get_or_create_url(request: HttpRequest) -> render:
    """
    Get or create an 'Url' object and create a shortened url
    :param request: HttpRequest
    :return: render
    """
    if request.method == 'POST':
        form = UrlForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            obj, created = Url.objects.get_or_create(
                base_url=cleaned_data['base_url'],
                user=request.user,
                defaults={'short_url': "".join(secrets.choice(chars) for _ in range(5))},
            )
            return render(request, 'bitly/result.html', {'obj': obj, 'created': created})
    else:
        form = UrlForm()
        return render(request, 'bitly/create_url.html', {'form': form})


@login_required
def redirect_by_url(request: HttpRequest, pk: int) -> HttpResponseRedirect:
    """
    Redirect from shortened url to real url
    :param request: HttpRequest
    :param pk: int
    :return: HttpResponseRedirect
    """
    obj = Url.objects.get(pk=pk)
    obj.counter += 1
    obj.save()
    return HttpResponseRedirect(obj.base_url)

templates/account_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
Account Profile Page
{% endblock %}

templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}style.css" />
    <title>{% block title %} Django Auth & Registration Templates {% endblock %}</title>
</head>

<body>
    <div id="header">
    {% block header %}
    <a href="{% url 'index' %}">{% trans "Home" %}</a> |

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }}
        (<a href="{% url 'logout' %}">{% trans "Log out" %}</a> |
        <a href="{% url 'password_change' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'login' %}">{% trans "Log in" %}</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>

    <div id="content">
    {% block content %}
    {% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
    {% endblock %}
    </div>
</body>

</html>

templates/bitly/create_url.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form }}
        <button type="submit">Get short url</button>
    </form>
    {% if form.errors %}
        <div class="alert alert-danger">
            {{ form.errors }}
        </div>
    {% endif %}
{% endblock %}

templates/bitly/result.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <a href="{% url 'bitly:redirect_by_url' pk=obj.pk %}">{{ request.get_host }}/{{ obj.short_url }}</a>
    {% if not created %}
        <p>Number of clicks on this link: {{ obj.counter }}</p>
    {% endif %}
{% endblock %}

templates/django_registration/activate.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<p>{% trans "Account activation failed" %}</p>

{% endblock %}

templates/django_registration/activation_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<p>{% trans "Your account is now activated." %}</p>
{% endblock %}

templates/django_registration/activation_failed.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<p>{% trans "Your account is now activated." %}</p>
{% endblock %}

templates/django_registration/registration_closed.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
	<p>{% trans "Registration is currently closed." %}</p>
{% endblock %}

templates/django_registration/registration_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<p>{% trans "You are now registered. Activation email sent." %}</p>
{% endblock %}

templates/django_registration/registration_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<form method="post" action=".">
  {% csrf_token %}
  {{ form.as_p }}

  <input type="submit" value="{% trans 'Submit' %}" />
</form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% if user.is_authenticated %}
    <a href="{% url 'bitly:create_url' %}">{% trans "create url" %}</a>
{% else %}
    <p>To get started, you need to login</p>
{% endif %}

{% endblock %}